### ISSUE TITLE
reaptcha links and readme on npmjs.com

### ISSUE THREAD

**Issue by marcodamm** [sarneeh/reaptcha#110]
The reaptcha presence at npmjs.com looks a little bit barren to me. There is no link to the github repo and no working Readme.

This initially raised some flags when I was looking for a suitable reCAPTCHA package, so you might want to consider to add some details to https://www.npmjs.com/package/reaptcha

**Comment by sarneeh** [comment]
Oh, thanks @marcodamm for reminding me about that! I've actually forgot about this. Will add all necessary informations to `npmjs` next time I'll sit down to `reaptcha` (which means sometime in february - don't have time earlier).
