### ISSUE TITLE
errors on unmount on edge 18

### ISSUE THREAD

**Issue by pospichalales** [sarneeh/reaptcha#118]
When I am leaving the page with reCAPTCHA displayed, the following errors are logged to console.
Edge 18.

reacaptcha__cs.js
Unable to get property 'create' of undefined or null reference

anchor
'recaptcha' is not defined

SCRIPT5007: SCRIPT5007: Object expected

They do not have negative effect to reCAPTCHA function but are logged to bugsnag every time as they are related to my page.

**Comment by pospichalales** [comment]
We probably need to remove Recaptcha scripts added to header when switching to different page (route)

**Comment by sarneeh** [comment]
@pospichalales Are you manually adding ReCAPTCHA scripts to the DOM? If yes, you could use `Reaptcha` automatic script injection - it cleans it up on component unmount (so it would get removed on route change).

**Comment by pospichalales** [comment]
I see if I go to page with Recaptcha in Chrome, then switch route and wait some time, this error is logged to console

![error](https://user-images.githubusercontent.com/47054776/52176050-d3ef1f80-27ad-11e9-8d53-44c81271d155.jpg)

**Comment by pospichalales** [comment]
This is probably different error, you can look here how they solved it https://github.com/dozoisch/react-google-recaptcha/pull/120

**Comment by sarneeh** [comment]
@pospichalales This error is already reported in #97 - let's keep it separate.

According to the error reported right here - I don't really know what can be the reason. I'll have to take a look why it's not being cleaned up on unmount. Unfortunately, I don't have time right now - I could look at it in 2-3 months. If it's very important for you, feel free to investigate and propose a PR :)

**Comment by sarneeh** [comment]
After a bit of investigation, this looks like some incompatibility of the recaptcha script with that specific version of Edge. Certainly not a bug in this library.
