### ISSUE TITLE
add getResponse method

### ISSUE THREAD

**Issue by tojacob** [sarneeh/reaptcha#133]
I am using this module with Nextjs (ssr) and it is the only one that works well. Thanks for that!

I'm combining it with Formik, and I'm needing the `grecaptcha.getResponse()` method, because the `onVerify` callback does not fit my need.

Is there any technical reason why it is not implemented?

**Comment by sarneeh** [comment]
@tojacob It is not implemented because you have the response already provided in the `onVerify` callback: `onVerify={(response) => {}}`. I don't see any reason why would you need the `getResponse` method?

**Comment by tojacob** [comment]
My problem is the way in which Formik runs.

I am using the invisible version of recaptcha, I run it on the `validate` hook of Formik.

After `validate`, if there are no errors, the` handleSubmit` is immediately executed. I can not find a way to pass the captcha result to the `handleSubmit`, because the` handleSubmit` would have to wait until the user makes the captcha.

Anyway I'll keep looking for a way to fix it, maybe I'm not doing it correctly or I'm missing something.

**Comment by tojacob** [comment]
Hello again. It is already solved.
Formik provides some very useful methods that can be used from the component.

Use some of them in the `onVerify` callback, as follows:

```javascript
onVerify={(res) => {
    props.setFieldValue ('recaptcha', res, false) // Add a value imperatively
    props.submitForm (); // send the form imperatively
}}
```

In the `handleSubmit` make the following validation before submitting the form:

```javascript
if (! values.recaptcha) {
    await this.recaptchaInstance.execute ();
    return;
}
```

This way you will continue with the submitting only when you receive the value of the recaptcha.
I leave it here in case some clueless like me should need it.

**Comment by sarneeh** [comment]
@tojacob Thanks for the solution!

After giving it a thought I guess it would be a good idea to add a `getResponse` method to expose the full Recaptcha API. So I'll keep this issue to remember about it for later :smile:

**Comment by sarneeh** [comment]
@tojacob I found even better option for your problem:
```js
<Reaptcha
    onVerify={token => {
        setFieldValue('token', token);
        submitForm();
    }
/>
...
<button 
    type="submit" 
    onClick={() => {
        setSubmitting(true);
        captcha.execute();
    }}
>
Submit
</button>
```

In this scenario you don't have to do the `if` statement in your `handleSubmit`. The `handleSubmit` will only run when the captcha verifies successfully.

**Comment by tojacob** [comment]
@sarneeh I see that it is easier to understand. Thank you.
