### ISSUE TITLE
support invisible dark mode

### ISSUE THREAD

**Issue by id-kemo** [sarneeh/reaptcha#136]
Hi @sarneeh, firstly I'd like to thank you for implementing reaptcha, it works great and is a true pleasure to use.

Not sure if it's an issue however, is there a reason why dark mode is not accessible when using Invisible variant of the ReCaptcha? Is it just an oversight?

https://github.com/sarneeh/reaptcha/blob/3ac319111e08fd0fc75e36d8275289fa78c5c2f6/lib/index.js#L144

Thanks,
Tom

**Comment by sarneeh** [comment]
@id-kemo I'm happy you like it! :smile: 

According to the dark mode... how does the invisible captcha behave in dark mode? Does the floating ReCAPTCHA indicator show in dark? If yes, that's surely an oversight :)

**Comment by id-kemo** [comment]
@sarneeh yes it does - I have only tried simple change from `rc-anchor-light` to `rc-anchor-dark` and it works as expected.

**Comment by sarneeh** [comment]
Published in `1.5.0`. Thank you @id-kemo!
