### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by mckelveygreg** [sarneeh/reaptcha#137]
I just wanted to say thank you for this library! I'm doing a Gatsby site and was super stuck using react-recaptcha because it wouldn't reset correctly and would only work on a single page load. 

I ended up finding you on another library's issue! https://github.com/appleboy/react-recaptcha/issues/228#issuecomment-397080544

However, I had a hard time finding you with just a search... I'm not sure how to get your SEO out there, but I did give you a tweet shout out :)

Thanks again!

**Comment by sarneeh** [comment]
Hey @mckelveygreg! Thank you very much for these words, I'm very happy it helped you in your work! :smile: I don't care much about SEO and the overall discoverability (as I don't have much time to work on it) but thanks a lot for the tweet! Have a great day and if you'll have any issues with `reaptcha` don't hesitate to file an issue! :)
