### ISSUE TITLE
server side rendering support

### ISSUE THREAD

**Issue by microadam** [sarneeh/reaptcha#14]
This assumes that `window` exists and so breaks when you try and render the component on the server side (to be later rehydrated on the client side). react-recpatcha doesn't have this issue (but does have others) so I was hoping to try and use this as an almost drop in replacement, but this is preventing that!

**Comment by sarneeh** [comment]
Thanks for the issue! Could you please give an example on how to crash it? Additionally, what's the error you're getting?

**Comment by sarneeh** [comment]
@microadam Please check out `reaptcha@next` version and tell if it fixes your issue 🚀

**Comment by richpowell** [comment]
looking forward to this.. but cant seem to load this branch via npm.. getting some errors

**Comment by sarneeh** [comment]
@richpowell No it did not got into the release unfortunately. Could you please check out the reaptcha@1.2.0-beta.0 version?

**Comment by sarneeh** [comment]
Released in `reaptcha@1.3.0`

**Comment by shahzadcacf** [comment]
where is documentation for SSR?

**Comment by sarneeh** [comment]
@shahzadcacf And why would you need a documentation for SSR? You use it normally as everything else.

**Comment by shahzadcacf** [comment]
Sorry i had a trouble in understanding how Google recaptcha works. i need to send g-recaptcha response to my API for validating.
