### ISSUE TITLE
Allow data attributes to be passed through to iframe

### ISSUE THREAD

**Issue by Undistraction** [sarneeh/reaptcha#147]
Please allow arbitrary data attributes to be passed through to the iframe. 

For example I use 'data-cy` to tag elements that I want to use in my Cypress tests. There is currently no way for me to tag the reaptcha iframe with an attribute.

**Comment by sarneeh** [comment]
@Undistraction Hmm... Actually `Reaptcha` does not control the iframe as it is controlled by the Google reCAPTCHA script. I'd need to research a bit to find out how to grasp this issue.

**Comment by Undistraction** [comment]
@sarneeth Actually, using a recaptcha in e2e tests is a terrible idea. Google actually supplies a set of keys for testing that means the recaptcha will always be satisfied. Means coming up with a means of getting keys to the component based on environment, but I think it is the only viable option.

**Comment by sarneeh** [comment]
@Undistraction Good that you found the answer to your problem! :)

**Comment by Undistraction** [comment]
@sarneeh Yes. And sorry for the noise.
