### ISSUE TITLE
Uncaught Error: Missing required parameters: sitekey

### ISSUE THREAD

**Issue by sachinsawant71** [sarneeh/reaptcha#154]
I get this error when I refresh my page which has Reaptcha component. Here is my code snippet. I confirmed that sitekey is being passed correctly to the component when I refresh the page.

                    <Reaptcha style={{ margin: "20px" }}
                        ref={e => this.recaptchaInstance = e}
                        sitekey={process.env.REACT_APP_CAPTCHA_SITEKEY}
                        onLoad={() => { }}
                        onVerify={this.captchaCallback}
                        onExpire={this.captchaExpiredCallback}
                    />

**Comment by sarneeh** [comment]
@sachinsawant71 What happens when you pass `sitekey` explicitly? (not via `process.env.REACT_APP_CAPTCHA_SITEKEY}`)

**Comment by sachinsawant71** [comment]
I tried it too. I hardcoded the site key into the component property but I am still getting same error.

**Comment by sarneeh** [comment]
@sachinsawant71 Do you have a `<script />` with Google reCAPTCHA in your site? If yes, delete it. `Reaptcha` injects the Google script by itself.

**Comment by sachinsawant71** [comment]
Thanks a lot. I had script for Google reCAPTCHA in the index.html. I removed it and it started working after "Refresh" too.

**Comment by sarneeh** [comment]
Awesome! :)

**Comment by danieldcm** [comment]
Confirmed. I had same issue after struggling to get recaptcha to work on my own, but finally  switching to use Reaptcha.  Thanks to google for redirecting me to this issue and for the quick resolution :).
