### ISSUE TITLE
How do I remove the connection error alert?

### ISSUE THREAD

**Issue by araujocristian** [sarneeh/reaptcha#156]
![image](https://user-images.githubusercontent.com/19674933/56964699-18325780-6b32-11e9-8bb1-6613748f27c4.png)

**Comment by sarneeh** [comment]
@araujocristian AFAIK Google reCAPTCHA script doesn't allow to control this alert. `Reaptcha` is just a wrapper for the Google reCAPTCHA script and does not provide any additional API.

**Comment by araujocristian** [comment]
Ah, ok! Thx!
