### ISSUE TITLE
add info about usage of Array.from in readme

### ISSUE THREAD

**Issue by gazcn007** [sarneeh/reaptcha#171]
This component doesn't work with IE yet, it throws `SCRIPT438: Object doesn't support property or method 'from'` error.

Repro steps:
1. Open any IE browser, go to the demo page : https://sarneeh.github.io/reaptcha/
2. Page appears to be blank
3. Open the console it shows `Object doesn't support property or method 'from'`:
![image](https://user-images.githubusercontent.com/12766318/59638789-2520ff80-910e-11e9-89b5-ee4b9197caea.png)

**Comment by sarneeh** [comment]
@gazcn007 Thank you for your report! Is this IE11? Apparently, this is due to `Array.from`.

https://github.com/sarneeh/reaptcha/blob/5be328601b8896cac296bd82f598844fe7e99725/lib/utils/isAnyScriptPresent.js#L3-L7

We would need to use some kind of polyfill for this. Unfortunately, I don't have time right now. I might come back to bugs/features for `reaptcha` somewhere in the next month.

**Comment by gazcn007** [comment]
Thanks for the fast reply! Ya for sure, no rush! Array.from is not supported on all IE browsers -> https://stackoverflow.com/questions/36810940/array-from-on-the-internet-explorer
So you can get a repro on any IE browser actually.

I will look into it to see if there is any quick fix for this meanwhile.

**Comment by ksocha** [comment]
I think the readme should contain the information that `Array.from` must be polyfilled in order for package to work. Including a polyfill will increase size of the bundle and most of the people already use some kind of polyfill solutions in their projects.

**Comment by sarneeh** [comment]
I agree with @ksocha that it should be handled by the users' side (use a polyfill). Not everyone wants to support IE and they would be forced to load additional KB of scripts. Let's add this info to readme.

**Comment by gazcn007** [comment]
yea ^ kk good that makes sense, we actually did a polyfill on our own, and it's all good.
Adding some notes to the README would be helpful!
