### ISSUE TITLE
Instance methods - better approach

### ISSUE THREAD

**Issue by ksocha** [sarneeh/reaptcha#175]
In the readme, it is stated: `If you have an idea how to do this better, feel free to file an issue to discuss it!`

It can be done easily with [render prop pattern](https://reactjs.org/docs/render-props.html).

Instead of doing:
```javascript
render = () => {
  return (
    <div id={this.props.id} className={this.props.className} ref={e => (this.container = e)} />
  );
};
```

We could do:
```javascript
render = () => {
  const component = (
    <div id={this.props.id} className={this.props.className} ref={e => (this.container = e)} />
  );

  return this.props.children
    ? this.props.children({
      renderExplicitly: this.renderExplicitly,
      reset: this.reset,
      execute: this.execute,
      recaptchaComponent: component,
    })
  : component;
};
```

And then the component could be used like:
```javascript
<Reaptcha
  sitekey={key}
  onLoad={onLoad}
  onVerify={onVerify}
  onExpire={onExpire}
  explicit
>
  {({ renderExplicitly, reset, execute, recaptchaComponent }) => (
    <div>
      {recaptchaComponent}
      <button onClick={reset}>Reset</button>
    </div>
  )}
</Reaptcha>
```

**Comment by sarneeh** [comment]
I love the idea! Wasn't familiar to render props at the time of building `reaptcha`. This could improve DX a little :smiley: Definitely gonna add this in `2.0`. Unfortunately, I'm still totally out of time, so this would need to wait for a little while.

**Comment by ksocha** [comment]
I can prepare a PR with required changes (or most of them). This could be added as a part of version 1.x.x because it is a non-breaking change.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sarneeh** [comment]
@ksocha I thought about removing the current way of using instance methods completely, but I guess we can keep both and just bump a minor version.
