### ISSUE TITLE
missing required parameters: sitekey

### ISSUE THREAD

**Issue by mahyar33** [sarneeh/reaptcha#18]
hi
I get this error

Uncaught Error: Missing required parameters: sitekey
    at new zr (recaptcha__en.js:392)
    at new es (recaptcha__en.js:400)
    at ss (recaptcha__en.js:411)
    at recaptcha__en.js:412
    at Array.forEach (<anonymous>)
    at ts (recaptcha__en.js:412)
    at bs (recaptcha__en.js:417)
    at cs (recaptcha__en.js:400)
    at recaptcha__en.js:419
    at recaptcha__en.js:429

but I entered sitekey and it works

**Comment by sarneeh** [comment]
@mahyar33 Show me please your `Reaptcha` instance.

**Comment by cmwd** [comment]
@mahyar33 Check if you're adding recaptcha script manually. I had the same problem after switching from another library.
Removing
```html
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
```
helped

**Comment by sarneeh** [comment]
@cmwd That could be right! I'll keep this issue and will do something to make this more intuitive and less missleading. Thanks!

**Comment by warent** [comment]
FYI I just encountered this problem too on the latest version of Reaptcha and @cmwd's fix worked

**Comment by sarneeh** [comment]
@warent I guess it's because of the URL. I'm checking only for the presence of:
https://github.com/sarneeh/reaptcha/blob/5d17fe2c15990d2b59904032f35b13ae0c54a936/lib/index.js#L38-L42
Have you been also injecting a script from `www.google.com` (not jus `google.com`)?

**Comment by warent** [comment]
Yep, you got it: `https://www.google.com/recaptcha/api.js`

**Comment by sarneeh** [comment]
@warent The issue has been fixed more comprehensively in `reaptcha@1.4.2`. Thanks for knowing about this! 😄

**Comment by warent** [comment]
@sarneeh Thanks for your work!

**Comment by fatclient** [comment]
I will be grateful for any help with this: got recaptcha on every page in footer (made by another library, so i do have <script /> in header with link to recaptcha api), and need some extra captchas of different type. This reaptcha throws "missing sitekey" error, when it provided and inject={false} is used. And of course, it doesn't call verify callBack .

**Comment by sarneeh** [comment]
@fatclient Could you please show how do you use `Reaptcha`?

**Comment by fatclient** [comment]
> @fatclient Could you please show how do you use `Reaptcha`?

I've created a gist https://gist.github.com/fatclient/2dcdccc0c4e816f82698f768c76871ea

**Comment by sarneeh** [comment]
@fatclient If you're using multiple recaptcha libs, how are you sure that `Reaptcha` is throwing the error? And are you sure that the `sitekey` is really being passed in (maybe it's undefined or something)? I'm curious because `Reaptcha` checks almost every possible case to just work properly and I'm almost certain that it's not the libs fault. Do you use multiple recaptcha libs on the same page, or on different ones (I mean, do they all work in parallel on some page, or separate?)

**Comment by fatclient** [comment]
> @fatclient If you're using multiple recaptcha libs, how are you sure that `Reaptcha` is throwing the error? 
Actually, now i'm not sure.  The error started to occur when i added your lib, but it's possible that it affects to another lib. I'll check that out.

> And are you sure that the `sitekey` is really being passed in (maybe it's undefined or something)? 
![default](https://user-images.githubusercontent.com/30300478/53285273-79dceb00-37aa-11e9-9604-2b316e3c468f.png)

> I'm curious because `Reaptcha` checks almost every possible case to just work properly and I'm almost certain that it's not the libs fault. Do you use multiple recaptcha libs on the same page, or on different ones (I mean, do they all work in parallel on some page, or separate?)

**Comment by fatclient** [comment]
Should I try to replace other recaptcha react solution with yours? Can it handle with several recaptchas of different type at once without conflicts?

**Comment by sarneeh** [comment]
@fatclient No problem mate, these kind of stuff happens to everyone :smile: Make sure that it's really problem with the wrong key, if not, come back and we'll try to figure out what's wrong!
