### ISSUE TITLE
add onClose callback for invisible mode

### ISSUE THREAD

**Issue by AndyOGo** [sarneeh/reaptcha#182]
If **invisible** mode can't auto-detect a human, it asks for a challenge like checkbox, selecting images, etc.
The user can close this overlay by clicking outside, but there is no way to handle this close by the component nor the offical Google API.

But there are some hacky ways, to poll it's state:
https://stackoverflow.com/questions/43488605/detect-when-challenge-window-is-closed-for-google-recaptcha

https://caniuse.com/#feat=mutationobserver

**Comment by sarneeh** [comment]
Hey! I'm sorry but I don't think i want to add this kind of hacks into the library. `reaptcha` should just expose the `Recaptcha` API, nothing else. The problem you're mentioning can be solved without adding anything to `reaptcha`.

**Comment by AndyOGo** [comment]
I thought that you wouldn't like.
I don't like it myself, though it's an annoying fact, that the recaptchad could ask the user for challenge like selecting images during invisible mode, which shows an overlay, which itself can be closed... but the API does not offer any callback, to be notified upon close 😞 🙍‍♂

**Comment by sarneeh** [comment]
@AndyOGo It's best to move to Recaptcha V3, which does not introduce any UI elements, everything is based on data.

> I had to give it a try at least^^

I appreciate the contribution! :)

**Comment by AndyOGo** [comment]
@sarneeh 
We evaluated V2 versus v3 for our use case, the main reason we can't/won't use v3 is that it would need to integrated into the whole user workflow.

Our product is a widget for integration in various apps at server outside of our control, that's why v3 isn't suitable for us.

Hehe, thank you. It's my pleasure, it's a joy to contribute to such clean projects! :)

**Comment by sarneeh** [comment]
> We evaluated V2 versus v3 for our use case, the main reason we can't/won't use v3 is that it would need to integrated into the whole user workflow.
> 
> Our product is a widget for integration in various apps at server outside of our control, that's why v3 isn't suitable for us.

Oh, I didn't think about this kind of use case.

> Hehe, thank you. It's my pleasure, it's a joy to contribute to such clean projects! :)

Thank you! 😄

**Comment by AndyOGo** [comment]
No worries, we just completely removed `invisible` mode and won't run into this close problem 🤦‍♂
