### ISSUE TITLE
Change lang and theme dynamically

### ISSUE THREAD

**Issue by robinalexandre** [sarneeh/reaptcha#193]
Hello there,

First, thanks for the library !

I have a question about `hl` and `theme` props:
The user of my app can change the theme or the lang of the app dynamically so I would like the reCaptcha to change according to his choice. 
But when I receive the props (let's say about the lang, it's the same process) in my component, and call `recaptchaRef.reset()`, the reCaptcha lang is still the same.. 

Am I doing something wrong ?

Thanks,
Alexandre

**Comment by sarneeh** [comment]
Hi! Unfortunately, it's a bug in the library. Will try to fix that in the nearest future.

**Comment by engmsilva** [comment]
I will follow up on this subject, as I also need to change the theme or the language dynamically.

**Comment by sarneeh** [comment]
Fixed in `1.10.0`
