### ISSUE TITLE
TypeError: this.captchaRef.getResponse is not a function

### ISSUE THREAD

**Issue by AndyOGo** [sarneeh/reaptcha#195]
Is `getResponse` really released in `reaptcha@1.7.2`?
Cause if I wanna use it, I get:
> TypeError: this.captchaRef.getResponse is not a function

```sh
npm ls reaptcha
@axa-ch/aletheia@1.23.9 ...\projects\aletheia
`-- reaptcha@1.7.2
```

https://unpkg.com/reaptcha@1.7.2/dist/index.js

**Comment by AndyOGo** [comment]
Sorry never mind, Webpack didn't get the update somehow.

**Comment by sarneeh** [comment]
😄
