### ISSUE TITLE
ng-recaptcha siteKey issue in angular

### ISSUE THREAD

**Issue by lakshmiprabhat** [sarneeh/reaptcha#200]
Hi, 
Iam getting "Missing required parameters: sitekey" error when i try to load Google recaptcha V2.
Am passing siteKey value from a service response in typescript.. Please help me resolve this issue.
My HTML Code,
<re-captcha (resolved)="resolved($event)" [siteKey] = "siteKeyVal" formControlName="recaptchareactive"></re-captcha>

Typescript code:
this.authService.getpropertyvalue('RECAPTCHA_PUBLIC_KEY').subscribe(
    result => { 
      this.siteKeyVal = <string>result;  
      
  }); 

Added this script in index.html ,
<script src="https://www.google.com/recaptcha/api.js" async defer></script>

**Comment by lakshmiprabhat** [comment]
Hi,
this issue got resolved after i used a Resolverservice..thanks .

**Comment by sarneeh** [comment]
Hey! But... This has nothing to do with this library, I'm confused 😅 Good that you've resolved it!
