### ISSUE TITLE
SameSite cookie error when using recaptcha through reaptcha

### ISSUE THREAD

**Issue by estebandee** [sarneeh/reaptcha#202]
Using reaptcha to display Google's Recaptcha, you can see the following error in the console:

```A cookie associated with a cross-site resource at https://google.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.```

**Comment by sarneeh** [comment]
This is 99,9% not fault of `reaptcha` - it's just injecting Google's code snippet and nothing else in terms of communication with Google. Have you tried clearing your cookies and trying again?

**Comment by estebandee** [comment]
Seems that the old cookies were stored alongside the new ones... clearing them did solve the issue. Thanks!
