### ISSUE TITLE
Reset not working

### ISSUE THREAD

**Issue by dharmendra-pegasusone** [sarneeh/reaptcha#222]
Hi,
i want to call reset when the captcha expires but it is not working.
but when i call reset on button click then it is working.
in my use case i have to go with 1 case how to achieve this. i am missing any thing?
on captcha expire i am calling this
const onCaptchaexpired = () => {
    
    recaptchaRef.current.reset();
   
  };

**Comment by sarneeh** [comment]
It works in the example: https://github.com/sarneeh/reaptcha/blob/master/example/src/modules/example.js.
Please provide a reproduction repo, otherwise I cannot really help you.

**Comment by sarneeh** [comment]
After investigating this a little, I found out that there's something wrong with how Recaptcha processes the events and unfortunately, running a reset right after expire does not work. The only workaround I found is to do:

```js
onExpires = () => {
  setTimeout(() => recaptchaRef.current.reset(), 0);
}
```

This is a bug in Google Recaptcha so I'm not willing to put workarounds like that into the library.
