### ISSUE TITLE
cleaning up recaptcha instances

### ISSUE THREAD

**Issue by stevenmunro** [sarneeh/reaptcha#26]
I have this loading inside a component that may be reloaded as part of a multi-step form process.

Upon reloading, as expected, it reloads Googles Recaptcha, and what we see are multiple 'bframes'.

I'm not sure if this would eventually lead to a memory leak (in extreme cases) but is there a way to clean this up a bit if the Recaptcha was no longer needed?

**Comment by sarneeh** [comment]
Hmm this seems like an oversight. I'll look at this issue next time sitting on this package, which will be nearest monday/tuesday 😄 Thank's for pointing this out!

**Comment by sarneeh** [comment]
Fixed in `reaptcha@1.3.0`.

**Comment by stevenmunro** [comment]
nice work!
