### ISSUE TITLE
recaptcha api validation

### ISSUE THREAD

**Issue by shahzadcacf** [sarneeh/reaptcha#37]
Need to validate the response from Recaptcha API.

**Comment by kradical** [comment]
I'll look into this over the next few days!

**Comment by sarneeh** [comment]
@kradical It might be that this is already implemented but I didn't ever used it and didn't have time to look into this. Check if some of the present methods could expose the Recaptcha API response 😄

**Comment by sarneeh** [comment]
@kradical Thanks for looking into the issue! I guess OP is asking about the Recaptcha response to be able to validate it on the server-side - but as I understand the [docs](https://developers.google.com/recaptcha/docs/verify) properly - this is already implemented into `reaptcha`. You get the Recaptcha response in the `onVerify` callback argument.

I would not want to add anything else into `reaptcha`. You should do API calls by yourself and you have everything needed to do so.

CC: @shahzadcacf

**Comment by kradical** [comment]
Makes sense, I think we can close this issue if that is the case. We could make a corresponding serverside package for this? But that might be overkill. I know in our use case we aren't using a library on our server and it isn't very much extra code or very complicated.

**Comment by sarneeh** [comment]
@kradical Yes, I think this would be an overkill 😄 I'm closing it for now. Again, thanks for taking the time to look at this issue, even if it didn't end with any PR 😄 

@shahzadcacf Please tell if this answers your problem.
