### ISSUE TITLE
unit testing

### ISSUE THREAD

**Issue by shahzadcacf** [sarneeh/reaptcha#94]
So i have implemented the Reapcha successfully. was wondering how can i mock google reCaptcha? My testing tools are
Jest,Enzyme

**Comment by shahzadcacf** [comment]
Thank you.

**Comment by shahzadcacf** [comment]
http://demo.dirbs.net/dvs/#/checkimei
So this is where i used reaptcha. After receiving response i enable the button and send API call. I am not able to mock the API call unless Google recaptcha response is received.

**Comment by sarneeh** [comment]
@shahzadcacf This is not enough information to know what's the real problem. Maybe show me your failing test.

**Comment by Bartuz** [comment]
I'm late to the party but struggled with it a bit. 

Here is what I came up with https://gist.github.com/Bartuz/baa4cb3cff45286a519acc5ad0313bd7

happily tested my component that way :)

**Comment by sarneeh** [comment]
@Bartuz Exactly what I was talking about! You just need to mock `window.recaptcha` and you're ready to go 😄

**Comment by Bartuz** [comment]
@sarneeh between`just` and `mock` there was an hour or so inverstigraging which parts of `window.grecaptcha` shall I mock to cause Reaptcha component to fire specific events. Definitely not just "just" :D Thanks anyway <3
